### PR TITLE
Add medium link to footer

### PR DESCRIPTION
**Pull request by kavehmz**
Is it OK if temple adds a medium link?

### CODE REVIEW

**Comment by aos** [comment]
Yes of course! Can you also update the [README](https://github.com/aos/temple/blob/master/README.md#customizing) example `config` to include the medium link under `author` as well?

**Comment by kavehmz** [comment]
Done. Please let me know if I missed something.

**Comment by aos** [comment]
LGTM!

**Comment by kavehmz** [comment]
Thanks

**Pull request merged**
